language: php
dist: trusty
sudo: false

php:
  - "8.0"

install:
  - composer install

script:
  - vendor/bin/phpcs -n --standard=PSR12 --ignore=./vendor/ --extensions=php ./
  - mkdir -p build/logs
  - mkdir -p .phpunit.cache/code-coverage
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
